## Exercises

### 1.

In [8]:
import torch

In [9]:
a = list(range(9))

In [10]:
a = torch.tensor(a);
a.size(),a.stride(),a.storage_offset()

(torch.Size([9]), (1,), 0)

In [11]:
b = a.view(3,3)

In [13]:
b.storage(),a.storage()

( 0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9])

In [15]:
c = b[1:,1:]
c.size(),c.storage_offset(),c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [16]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

### 2.

In [17]:
func = torch.sin

In [18]:
func(a)

RuntimeError: sin_vml_cpu not implemented for 'Long'

In [19]:
func(a.float())

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])

In [20]:
func = torch.sin_

In [22]:
func(a.float())

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])

In [27]:
torch.sin_(a.float())

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])

In [28]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
func(a.to(dtype=float))

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894], dtype=torch.float64)

In [30]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])